[workspace]
members = [
    "bytestream",
    "elf64",
    "librust",
    "sbi",
    "tar",
    "vanadinite",
    "vanadinite_macros",
] #"fat32",
resolver = "2"

[profile.release]
#debug = true
lto = "thin"
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 2
